In [3]:
import os
import sys

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import torch

# Ajoute le package local `src` pour pouvoir l'utiliser dans un notebook
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.utils.random import set_manual_seed
from src.data.loader import load_behavior

set_manual_seed(5330)

In [4]:
PATH_DATA = "training_180140_behavior_sequence.txt"

In [5]:
load_behavior(PATH_DATA)

           id      rip   api
0   382095360  4089672   338
1   382095360  4089680   496
2   382095360  4089688  1199
3   382095360  4089700   103
4   382095360  4084178   676
5   382095360  4084199  2063
6   382095360  4089089  2567
7   382095360  4088709  1586
8   382095360  4088739   597
9   382095360  4088752   597
10  382095360  4088765   597
11  382095360  4088778   597
12  382095360  4088862   524
13  382095360  4088885  2332
14  382095360  4087942   519
15  382095360  4089822   519
16  382095360  4088912   519
17  382095360  4088925   519
18  382095360  4088938   519
19  382095360  4088951   519
20  382095360  4089874    52
21  382095360  4089874    52
22  382095360  4089874    52
23  382095360  4089874    52
24  382095360  4089874    52
25  382095360  4089874    52
26  382095360  4089874    52
27  382095360  4089874    52
28  382095360  4089874    52